"""init

Revision ID: 6d71eb5d75d5
Revises: 
Create Date: 2026-01-10 22:56:03.159886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d71eb5d75d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kran', 'description_uz',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('kran', 'description_ru',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kran', 'description_ru',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('kran', 'description_uz',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    # ### end Alembic commands ###
